export interface Question {
  id: string;
  text: string;
  options?: string[];
  type: "select" | "text";
  placeholder?: string;
  explanation?: string;
  condition?: (answers: Record<string, string>) => boolean;
}

export const noWillQuestions: Question[] = [
  {
    id: "fullName",
    text: "מהו שמך המלא?",
    type: "text",
    placeholder: "שם פרטי ושם משפחה",
    explanation: "השם ישמש בנוסח הצוואה הראשוני בלבד.",
  },
  {
    id: "familyStructure",
    text: "מהו המבנה המשפחתי שלך?",
    type: "select",
    options: [
      "בן/בת זוג וילדים משותפים",
      "בן/בת זוג וילדים מקשר קודם",
      "ללא בן/בת זוג אך עם ילדים",
      "בן/בת זוג ללא ילדים",
      "ללא בן/בת זוג וללא ילדים",
      "מבנה משפחתי מורכב אחר",
    ],
    explanation: "שאלה זו קובעת את מבנה ההורשה הבסיסי.",
  },
  {
    id: "inheritanceModel",
    text: "איזה מודל הורשה מתאים יותר לרצונך?",
    type: "select",
    options: [
      "כל העיזבון לבן/בת הזוג",
      "בן/בת הזוג קודם ואחריו יורשים נוספים",
      "חלוקה ישירה בין כמה יורשים",
      "חלוקה לא שוויונית או מותאמת אישית",
      "עדיין לא בטוח/ה",
    ],
    explanation: "כאן נקבע האם מדובר במודל פשוט או במנגנון מורכב יותר.",
  },
  {
    id: "multipleHeirs",
    text: "האם תרצה/י לצוות ליותר מיורש אחד?",
    type: "select",
    options: ["כן", "לא"],
    explanation: "הבחנה חשובה בין הורשה לאדם אחד לבין חלוקה בין כמה יורשים.",
  },
  {
    id: "distributionMethod",
    text: "אם יש כמה יורשים — כיצד תרצה/י לחלק את העיזבון?",
    type: "select",
    options: [
      "בחלקים שווים",
      "בחלקים לא שווים",
      "באחוזים",
      "בנכסים מסוימים לכל אחד",
      "טרם החלטתי",
    ],
    explanation: "חלוקה באחוזים, בחלקים או לפי נכס מסוים מייצרת נוסח שונה.",
    condition: (a) => a.multipleHeirs === "כן",
  },
  {
    id: "specialAssetInstruction",
    text: "האם יש נכס מסוים שחשוב לך לקבוע לגביו הוראה מיוחדת?",
    type: "select",
    options: ["כן", "לא"],
    explanation: "למשל דירה, עסק, חשבון, כספת או נכס אחר.",
  },
  {
    id: "specialAssetDetails",
    text: "נא לתאר בקצרה את הנכס ואת ההוראה המבוקשת",
    type: "text",
    placeholder: "לדוגמה: דירה ברחוב..., תימכר / תועבר / תינתן זכות קדימה",
    explanation: "מידע זה ישמש לבניית סעיף ייעודי בטיוטה.",
    condition: (a) => a.specialAssetInstruction === "כן",
  },
  {
    id: "substituteHeir",
    text: "אם אחד היורשים ילך לעולמו לפניך או לפני קבלת חלקו, האם חשוב לך לקבוע מי יבוא במקומו?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "זהו מנגנון של 'יורש במקום יורש'.",
  },
  {
    id: "substituteHeirMode",
    text: "מה צריך לקרות במקרה כזה?",
    type: "select",
    options: [
      "חלקו יעבור לצאצאיו",
      "חלקו יחזור לשאר היורשים היחסיים",
      "אדם אחר ייכנס במקומו",
      "טרם החלטתי",
    ],
    explanation: "מנגנון זה משנה באופן מהותי את נוסח הצוואה.",
    condition: (a) => a.substituteHeir === "כן",
  },
  {
    id: "successiveHeir",
    text: "האם תרצה/י שהרכוש יעבור תחילה לאדם אחד, ורק לאחר מכן ליורש אחר?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "זהו מנגנון של 'יורש אחר יורש'.",
  },
  {
    id: "successiveHeirDetails",
    text: "מי היורש הראשון ומי היורש הבא אחריו?",
    type: "text",
    placeholder: "לדוגמה: בן הזוג תחילה, ולאחר פטירתו הילדים",
    explanation: "השאלה קובעת אם נדרש מנגנון של יורש אחר יורש.",
    condition: (a) => a.successiveHeir === "כן",
  },
  {
    id: "minorChildren",
    text: "האם יש קטינים או יורשים שתרצה לדחות את קבלת חלקם לגיל מסוים?",
    type: "select",
    options: ["כן", "לא"],
    explanation: "רלוונטי במיוחד לקטינים או לדחיית קבלת ירושה.",
  },
  {
    id: "minorChildrenDetails",
    text: "מהו ההסדר הרצוי?",
    type: "select",
    options: [
      "ניהול עד גיל מסוים",
      "מסירת הכספים בשלבים",
      "מינוי אדם שינהל עד להתקיים תנאי",
      "טרם החלטתי",
    ],
    explanation: "שאלה זו נוגעת לניהול ירושה עד לתנאי עתידי.",
    condition: (a) => a.minorChildren === "כן",
  },
  {
    id: "executorNeeded",
    text: "האם תרצה/י למנות מנהל עיזבון?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "מומלץ במיוחד בחלוקה מורכבת, סכסוכים, ריבוי יורשים או נכסים.",
  },
  {
    id: "executorName",
    text: "אם כן, מי האדם שתרצה/י לשקול כמנהל עיזבון?",
    type: "text",
    placeholder: "שם מלא",
    explanation: "אפשר גם להשלים פרט זה בהמשך.",
    condition: (a) => a.executorNeeded === "כן",
  },
  {
    id: "executorProtections",
    text: "האם חשוב לך שלמנהל העיזבון יהיו הגנות וסמכות להסתמך על אנשי מקצוע?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "מנגנון חשוב במקרים של נכסים, שמאות, חלוקה או ביצוע מורכב.",
    condition: (a) => a.executorNeeded === "כן",
  },
  {
    id: "conflictRisk",
    text: "האם יש חשש ממשי למחלוקת בין היורשים?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "אם כן, יש מקום להוסיף מנגנוני הגנה והבהרה.",
  },
  {
    id: "conflictProtection",
    text: "האם חשוב לך להוסיף מנגנונים לצמצום מחלוקות?",
    type: "select",
    options: [
      "כן, לרבות שמאות / הערכת שווי",
      "כן, לרבות מנגנון נגד התנגדות לצוואה",
      "כן, שניהם",
      "לא",
      "לא בטוח/ה",
    ],
    explanation: "רלוונטי כאשר רוצים להקטין התנגדויות ומחלוקות עתידיות.",
    condition: (a) => a.conflictRisk === "כן" || a.conflictRisk === "לא בטוח/ה",
  },
  {
    id: "rightOfFirstRefusal",
    text: "האם יש אדם שתרצה/י לתת לו זכות קדימה לרכוש נכס מתוך העיזבון?",
    type: "select",
    options: ["כן", "לא"],
    explanation: "למשל זכות קדימה לרכישת דירה.",
  },
  {
    id: "rightOfFirstRefusalDetails",
    text: "נא לפרט את הנכס ואת בעל זכות הקדימה",
    type: "text",
    placeholder: "לדוגמה: הדירה ב..., זכות קדימה ל...",
    explanation: "ישמש ליצירת סעיף ייעודי בטיוטה.",
    condition: (a) => a.rightOfFirstRefusal === "כן",
  },
  {
    id: "specificCharge",
    text: "האם תרצה/י להטיל חיוב על יורש מסוים?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "למשל תשלום לאדם אחר, מתן זכות שימוש, או ביצוע פעולה מסוימת.",
  },
  {
    id: "specificChargeDetails",
    text: "נא לפרט מהו החיוב המבוקש",
    type: "text",
    placeholder: "לדוגמה: תשלום סכום מסוים / מתן זכות שימוש / שמירה על נכס",
    explanation: "רלוונטי למנגנון של 'חיוב יורש'.",
    condition: (a) => a.specificCharge === "כן",
  },
  {
    id: "digitalAssets",
    text: "האם יש לך נכסים דיגיטליים, חשבונות מקוונים או מידע דיגיטלי שחשוב להסדיר?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "המערכת תוכל להוסיף התייחסות ראשונית לכך בטיוטה.",
  },
  {
    id: "burialAndMemorial",
    text: "האם תרצה/י לכלול הוראות לגבי הוצאות קבורה, שבעה או אזכרות?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
    explanation: "רלוונטי כאשר רוצים לקבוע מנגנון תשלום מתוך העיזבון.",
  },
  {
    id: "provideIdNow",
    text: "האם להזין עכשיו תעודת זהות? (לא חובה)",
    type: "select",
    options: ["כן", "לא"],
    explanation: "אפשר להשלים גם בהמשך.",
  },
  {
    id: "idNumber",
    text: "מהו מספר תעודת הזהות שלך?",
    type: "text",
    placeholder: "מספר תעודת זהות",
    condition: (a) => a.provideIdNow === "כן",
  },
  {
    id: "provideAddressNow",
    text: "האם להזין עכשיו כתובת מגורים? (לא חובה)",
    type: "select",
    options: ["כן", "לא"],
    explanation: "אפשר להשלים גם בהמשך.",
  },
  {
    id: "address",
    text: "מהי כתובת מגוריך?",
    type: "text",
    placeholder: "רחוב, מספר, עיר",
    condition: (a) => a.provideAddressNow === "כן",
  },
];

export const existingWillQuestions: Question[] = [
  {
    id: "existingWillType",
    text: "איזו צוואה קיימת אצלך כיום?",
    type: "select",
    options: ["צוואה רגילה", "צוואה הדדית", "לא בטוח/ה"],
    explanation: "שלב ראשון בבדיקת צורך בעדכון.",
  },
  {
    id: "familyChanged",
    text: "האם חל שינוי במצב המשפחתי מאז עריכת הצוואה?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
  },
  {
    id: "assetsChanged",
    text: "האם נוספו נכסים משמעותיים מאז עריכת הצוואה?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
  },
  {
    id: "mechanismMissing",
    text: "האם לדעתך חסר בצוואה מנגנון חשוב (למשל יורש חלופי, מנהל עיזבון, הוראה לנכס מסוים)?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
  },
  {
    id: "digitalAssets",
    text: "האם קיימים כיום נכסים דיגיטליים שאינם מוסדרים בצוואה?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
  },
  {
    id: "conflictRisk",
    text: "האם יש חשש למחלוקת בין היורשים?",
    type: "select",
    options: ["כן", "לא", "לא בטוח/ה"],
  },
];
